% Name - Surag P
% Roll No. - 181EC248

% Experimment Five

%Simulation of Frequency Division Multiplexing and Demultiplexing

%Pre-Lab

%1. Explain multiplexing?
%Ans- Combining multiple messages into a single signal for transmission is Multiplexing.

%2. Explain different types of multiplexing?
%Ans- There are two types of multiplexing
%     a.Frequency division multiplexing
%       Signals of different frequencies are multiplexed for transmission.
%     b.Time division Multiplexing
%       This is a method of putting multiple data streams in a single signal by separating the signal into many segments

%3. What are the advantages of multiplexing?
%Ans- Multiplexing allows us to make use of resources more efficiently by allowing us to transmit more information using a single signal.

%Generating Input Signals 

Fs = 100; 
t = [0:2*Fs+1]'/Fs;
%Signal 1
x1 = sin(2*pi*2*t);             
z1 = fft(x1);
z1=abs(z1);
%Signal 2
x2 = sin(2*pi*6*t);              
z2 = fft(x2);
z2=abs(z2);
%Signal 3
x3 = sin(2*pi*12*t);              
z3 = fft(x3);
z3=abs(z3);

figure;
subplot(3,1,1);
plot(x1(1:200));
title('Signal 1');
xlabel('t');
ylabel('Amplitude');
subplot(3,1,2);
plot(x2(1:200));
title('Signal 2');
xlabel('t');
ylabel('Amplitude');
subplot(3,1,3);
plot(x3(1:200));
title('signal 3');
xlabel('t');
ylabel('Amplitude');

figure;
subplot(3,1,1);
plot(z1(1:200));
title('Spectrum of signal 1');
xlabel('f');
ylabel('Magnitude');
subplot(3,1,2);
plot(z2(1:200));
title('Spectrum of signal 2');
xlabel('f')
ylabel('Magnitude');
subplot(3,1,3);
plot(z3(1:200));
title('Spectrum of signal 3');
xlabel('f')
ylabel('Magnitude');

z=z1+z2+z3;
figure;
plot(z(1:200));
title('Frequency Multiplexed Signals');

figure;
%Filter For Signal 1 (values abtained from the spectrum graph)
f1=[ones(10,1); zeros(182,1); ones(10,1)];
dz1=z.*f1;
d1 = ifft(dz1);
subplot(3,1,1)
plot(t(1:200)*100,d1(1:200));
title('Signal 1 Recovered');
xlabel('t');
ylabel('Amplitude');

%Filter For Signal 2  (values abtained from the spectrum graph)
f2=[zeros(8,1);ones(10,1);zeros(166,1);ones(10,1);zeros(8,1)];
dz2=z.*f2;
d2 = ifft(dz2);
subplot(3,1,2);
plot(t(1:200)*100,d2(1:200));
title('Signal 2 Recovered');
xlabel('t');
ylabel('Amplitude');

%Filter For Signal 3  (values abtained from the spectrum graph)
f3=[zeros(20,1);ones(30,1);zeros(102,1);ones(30,1);zeros(20,1)];
dz3=z.*f3;
d3 = ifft(dz3); subplot(3,1,3);
plot(t(1:200)*100,d3(1:200)); 
title('Signal 3 Recovered');
xlabel('t');
ylabel('Amplitude');

%Post-lab
%1. Explain Frequency-division multiplexing
%Ans- In FDM ,the total bandwidth available in a communication medium is divided into a many of non-overlapping frequency bands, each of which is used to carry a separate message. Thus simultaneous transmission of multiple signals together.
%2. Differentiate FDM & TDM
%FDM -Frequency division multiplexing
%Here signals of different frequencies are multiplexed together for transmission.
%TDM - Time division Multiplexing
%Here, samples of different signals are transmitted together by interleaving portions over time rather than frequency.
%3. What is the BW of FDM
%The range of frequencies occupied by the multiplexed signal in FDM is called the bandwidth.In the case of voice communications, each user is allocated a bandwidth of 4 kHz which provides good quality.
%4. Explain FDM Generation
%In FDM, signals generated by each sending device modulate different carrier frequencies. These modulated signals are then combined into a single composite signal that can be transported by the link. Carrier frequencies are separated by sufficient bandwidth to accommodate the modulated signal.